// packages/solid/src/create-envelope.tsx
import { onMount, createSignal, createMemo } from "solid-js";

export type EmbedCreateEnvelopeProps = {
  className?: string;
  host?: string;
  presignToken: string;
  externalId?: string;
  user?: {
    name?: string;
    email?: string;
  };
  type: "DOCUMENT" | "TEMPLATE";
  folderId?: string;
  css?: string | undefined;
  cssVars?: (CssVars & Record<string, string>) | undefined;
  darkModeDisabled?: boolean | undefined;
  language?: string | undefined;

  // biome-ignore lint/suspicious/noExplicitAny: Hehe
  features?: DeepPartial<EnvelopeEditorSettings> & Record<string, any>;
  onEnvelopeCreated?: (data: {
    externalId: string | null;
    envelopeId: number;
  }) => void;
};

import { CssVars } from "./css-vars";
import type { DeepPartial, EnvelopeEditorSettings } from "./features-type";

function EmbedCreateEnvelope(props: EmbedCreateEnvelopeProps) {
  const src = createMemo(() => {
    const appHost = props.host || "https://app.documenso.com";
    const encodedOptions = btoa(
      encodeURIComponent(
        JSON.stringify({
          externalId: props.externalId,
          user: props.user,
          type: props.type,
          folderId: props.folderId,
          features: props.features,
          css: props.css,
          cssVars: props.cssVars,
          darkModeDisabled: props.darkModeDisabled,
          language: props.language,
        })
      )
    );
    const srcUrl = new URL(`/embed/v2/authoring/envelope/create`, appHost);
    srcUrl.searchParams.set("token", props.presignToken);
    srcUrl.hash = encodedOptions;
    return srcUrl.toString();
  });

  const sandbox = createMemo(() => {
    // biome-ignore lint/suspicious/noExplicitAny: Mitosis types `sandbox` as a single token, but the attribute is space-separated.
    return "allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox allow-storage-access-by-user-activation" as any;
  });

  function handleMessage(event: MessageEvent) {
    if (__iframe?.contentWindow === event.source) {
      switch (event.data.type) {
        case "envelope-created":
          props.onEnvelopeCreated?.({
            envelopeId: event.data.envelopeId,
            externalId: event.data.externalId,
          });
          break;
      }
    }
  }

  let __iframe!: HTMLIFrameElement;

  onMount(() => {
    window.addEventListener("message", handleMessage);
  });

  return (
    <>
      <iframe
        class={props.className}
        ref={__iframe!}
        src={src()}
        sandbox={sandbox()}
      ></iframe>
    </>
  );
}

export default EmbedCreateEnvelope;

// packages/svelte/src/create-envelope.svelte
<script context="module" lang="ts">
  export type EmbedCreateEnvelopeProps = {
    className?: string;
    host?: string;
    presignToken: string;
    externalId?: string;
    user?: {
      name?: string;
      email?: string;
    };
    type: "DOCUMENT" | "TEMPLATE";
    folderId?: string;
    css?: string | undefined;
    cssVars?: (CssVars & Record<string, string>) | undefined;
    darkModeDisabled?: boolean | undefined;
    language?: string | undefined;

    // biome-ignore lint/suspicious/noExplicitAny: Hehe
    features?: DeepPartial<EnvelopeEditorSettings> & Record<string, any>;
    onEnvelopeCreated?: (data: {
      externalId: string | null;
      envelopeId: number;
    }) => void;
  };
</script>

<script lang="ts">
  import { onDestroy, onMount } from "svelte";

  import { CssVars } from "./css-vars";
  import type { DeepPartial, EnvelopeEditorSettings } from "./features-type";

  export let host: EmbedCreateEnvelopeProps["host"] = undefined;
  export let externalId: EmbedCreateEnvelopeProps["externalId"] = undefined;
  export let user: EmbedCreateEnvelopeProps["user"] = undefined;
  export let type: EmbedCreateEnvelopeProps["type"];
  export let folderId: EmbedCreateEnvelopeProps["folderId"] = undefined;
  export let features: EmbedCreateEnvelopeProps["features"] = undefined;
  export let css: EmbedCreateEnvelopeProps["css"] = undefined;
  export let cssVars: EmbedCreateEnvelopeProps["cssVars"] = undefined;
  export let darkModeDisabled: EmbedCreateEnvelopeProps["darkModeDisabled"] =
    undefined;
  export let language: EmbedCreateEnvelopeProps["language"] = undefined;
  export let presignToken: EmbedCreateEnvelopeProps["presignToken"];
  export let onEnvelopeCreated: EmbedCreateEnvelopeProps["onEnvelopeCreated"] =
    undefined;
  export let className: EmbedCreateEnvelopeProps["className"] = undefined;

  function handleMessage(event: MessageEvent) {
    if (__iframe?.contentWindow === event.source) {
      switch (event.data.type) {
        case "envelope-created":
          onEnvelopeCreated?.({
            envelopeId: event.data.envelopeId,
            externalId: event.data.externalId,
          });
          break;
      }
    }
  }
  $: src = () => {
    const appHost = host || "https://app.documenso.com";
    const encodedOptions = btoa(
      encodeURIComponent(
        JSON.stringify({
          externalId: externalId,
          user: user,
          type: type,
          folderId: folderId,
          features: features,
          css: css,
          cssVars: cssVars,
          darkModeDisabled: darkModeDisabled,
          language: language,
        })
      )
    );
    const srcUrl = new URL(`/embed/v2/authoring/envelope/create`, appHost);
    srcUrl.searchParams.set("token", presignToken);
    srcUrl.hash = encodedOptions;
    return srcUrl.toString();
  };
  $: sandbox = () => {
    // biome-ignore lint/suspicious/noExplicitAny: Mitosis types `sandbox` as a single token, but the attribute is space-separated.
    return "allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox allow-storage-access-by-user-activation" as any;
  };

  let __iframe;

  onMount(() => {
    window.addEventListener("message", handleMessage);
  });

  onDestroy(() => {
    window.removeEventListener("message", handleMessage);
  });
</script>

<iframe
  bind:this={__iframe}
  class={className}
  src={src()}
  sandbox={sandbox()}
/>
