// packages/solid/src/update-envelope.tsx
import { onMount, createSignal, createMemo } from "solid-js";

export type EmbedUpdateEnvelopeProps = {
  className?: string;
  host?: string;
  presignToken: string;
  externalId?: string;
  user?: {
    name?: string;
    email?: string;
  };
  envelopeId: string;
  css?: string | undefined;
  cssVars?: (CssVars & Record<string, string>) | undefined;
  darkModeDisabled?: boolean | undefined;
  language?: string | undefined;

  // biome-ignore lint/suspicious/noExplicitAny: Hehe
  features?: DeepPartial<EnvelopeEditorSettings> & Record<string, any>;
  onEnvelopeUpdated?: (data: {
    externalId: string | null;
    envelopeId: string;
  }) => void;
};

import { CssVars } from "./css-vars";
import type { DeepPartial, EnvelopeEditorSettings } from "./features-type";

function EmbedUpdateEnvelope(props: EmbedUpdateEnvelopeProps) {
  const src = createMemo(() => {
    const appHost = props.host || "https://app.documenso.com";
    const encodedOptions = btoa(
      encodeURIComponent(
        JSON.stringify({
          externalId: props.externalId,
          user: props.user,
          features: props.features,
          css: props.css,
          cssVars: props.cssVars,
          darkModeDisabled: props.darkModeDisabled,
          language: props.language,
        })
      )
    );
    const srcUrl = new URL(
      `/embed/v2/authoring/envelope/edit/${props.envelopeId}`,
      appHost
    );
    srcUrl.searchParams.set("token", props.presignToken);
    srcUrl.hash = encodedOptions;
    return srcUrl.toString();
  });

  const sandbox = createMemo(() => {
    // biome-ignore lint/suspicious/noExplicitAny: Mitosis types `sandbox` as a single token, but the attribute is space-separated.
    return "allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox allow-storage-access-by-user-activation" as any;
  });

  function handleMessage(event: MessageEvent) {
    if (__iframe?.contentWindow === event.source) {
      switch (event.data.type) {
        case "envelope-updated":
          props.onEnvelopeUpdated?.({
            envelopeId: event.data.envelopeId,
            externalId: event.data.externalId,
          });
          break;
      }
    }
  }

  let __iframe!: HTMLIFrameElement;

  onMount(() => {
    window.addEventListener("message", handleMessage);
  });

  return (
    <>
      <iframe
        class={props.className}
        ref={__iframe!}
        src={src()}
        sandbox={sandbox()}
      ></iframe>
    </>
  );
}

export default EmbedUpdateEnvelope;

// packages/svelte/src/update-envelope.svelte
<script context="module" lang="ts">
  export type EmbedUpdateEnvelopeProps = {
    className?: string;
    host?: string;
    presignToken: string;
    externalId?: string;
    user?: {
      name?: string;
      email?: string;
    };
    envelopeId: string;
    css?: string | undefined;
    cssVars?: (CssVars & Record<string, string>) | undefined;
    darkModeDisabled?: boolean | undefined;
    language?: string | undefined;

    // biome-ignore lint/suspicious/noExplicitAny: Hehe
    features?: DeepPartial<EnvelopeEditorSettings> & Record<string, any>;
    onEnvelopeUpdated?: (data: {
      externalId: string | null;
      envelopeId: string;
    }) => void;
  };
</script>

<script lang="ts">
  import { onDestroy, onMount } from "svelte";

  import { CssVars } from "./css-vars";
  import type { DeepPartial, EnvelopeEditorSettings } from "./features-type";

  export let host: EmbedUpdateEnvelopeProps["host"] = undefined;
  export let externalId: EmbedUpdateEnvelopeProps["externalId"] = undefined;
  export let user: EmbedUpdateEnvelopeProps["user"] = undefined;
  export let features: EmbedUpdateEnvelopeProps["features"] = undefined;
  export let css: EmbedUpdateEnvelopeProps["css"] = undefined;
  export let cssVars: EmbedUpdateEnvelopeProps["cssVars"] = undefined;
  export let darkModeDisabled: EmbedUpdateEnvelopeProps["darkModeDisabled"] =
    undefined;
  export let language: EmbedUpdateEnvelopeProps["language"] = undefined;
  export let envelopeId: EmbedUpdateEnvelopeProps["envelopeId"];
  export let presignToken: EmbedUpdateEnvelopeProps["presignToken"];
  export let onEnvelopeUpdated: EmbedUpdateEnvelopeProps["onEnvelopeUpdated"] =
    undefined;
  export let className: EmbedUpdateEnvelopeProps["className"] = undefined;

  function handleMessage(event: MessageEvent) {
    if (__iframe?.contentWindow === event.source) {
      switch (event.data.type) {
        case "envelope-updated":
          onEnvelopeUpdated?.({
            envelopeId: event.data.envelopeId,
            externalId: event.data.externalId,
          });
          break;
      }
    }
  }
  $: src = () => {
    const appHost = host || "https://app.documenso.com";
    const encodedOptions = btoa(
      encodeURIComponent(
        JSON.stringify({
          externalId: externalId,
          user: user,
          features: features,
          css: css,
          cssVars: cssVars,
          darkModeDisabled: darkModeDisabled,
          language: language,
        })
      )
    );
    const srcUrl = new URL(
      `/embed/v2/authoring/envelope/edit/${envelopeId}`,
      appHost
    );
    srcUrl.searchParams.set("token", presignToken);
    srcUrl.hash = encodedOptions;
    return srcUrl.toString();
  };
  $: sandbox = () => {
    // biome-ignore lint/suspicious/noExplicitAny: Mitosis types `sandbox` as a single token, but the attribute is space-separated.
    return "allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox allow-storage-access-by-user-activation" as any;
  };

  let __iframe;

  onMount(() => {
    window.addEventListener("message", handleMessage);
  });

  onDestroy(() => {
    window.removeEventListener("message", handleMessage);
  });
</script>

<iframe
  bind:this={__iframe}
  class={className}
  src={src()}
  sandbox={sandbox()}
/>
