// packages/vue/src/update-envelope.vue
<template>
  <iframe
    ref="__iframe"
    :class="className"
    :src="src"
    :sandbox="sandbox"
  ></iframe>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue";

import { CssVars } from "./css-vars";
import type { DeepPartial, EnvelopeEditorSettings } from "./features-type";

export type EmbedUpdateEnvelopeProps = {
  className?: string;
  host?: string;
  presignToken: string;
  externalId?: string;
  user?: {
    name?: string;
    email?: string;
  };
  envelopeId: string;
  css?: string | undefined;
  cssVars?: (CssVars & Record<string, string>) | undefined;
  darkModeDisabled?: boolean | undefined;
  language?: string | undefined;

  // biome-ignore lint/suspicious/noExplicitAny: Hehe
  features?: DeepPartial<EnvelopeEditorSettings> & Record<string, any>;
  onEnvelopeUpdated?: (data: {
    externalId: string | null;
    envelopeId: string;
  }) => void;
};

const props = defineProps<EmbedUpdateEnvelopeProps>();

const __iframe = ref<HTMLIFrameElement>(null);

onMounted(() => {
  window.addEventListener("message", handleMessage);
});
onUnmounted(() => {
  window.removeEventListener("message", handleMessage);
});
const src = computed(() => {
  const appHost = props.host || "https://app.documenso.com";
  const encodedOptions = btoa(
    encodeURIComponent(
      JSON.stringify({
        externalId: props.externalId,
        user: props.user,
        features: props.features,
        css: props.css,
        cssVars: props.cssVars,
        darkModeDisabled: props.darkModeDisabled,
        language: props.language,
      })
    )
  );
  const srcUrl = new URL(
    `/embed/v2/authoring/envelope/edit/${props.envelopeId}`,
    appHost
  );
  srcUrl.searchParams.set("token", props.presignToken);
  srcUrl.hash = encodedOptions;
  return srcUrl.toString();
});
const sandbox = computed(() => {
  // biome-ignore lint/suspicious/noExplicitAny: Mitosis types `sandbox` as a single token, but the attribute is space-separated.
  return "allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox allow-storage-access-by-user-activation" as any;
});

function handleMessage(event: MessageEvent) {
  if (__iframe.value?.contentWindow === event.source) {
    switch (event.data.type) {
      case "envelope-updated":
        props.onEnvelopeUpdated?.({
          envelopeId: event.data.envelopeId,
          externalId: event.data.externalId,
        });
        break;
    }
  }
}
</script>

// packages/react/src/update-envelope.tsx
"use client";
import * as React from "react";
import { useRef, useEffect } from "react";

export type EmbedUpdateEnvelopeProps = {
  className?: string;
  host?: string;
  presignToken: string;
  externalId?: string;
  user?: {
    name?: string;
    email?: string;
  };
  envelopeId: string;
  css?: string | undefined;
  cssVars?: (CssVars & Record<string, string>) | undefined;
  darkModeDisabled?: boolean | undefined;
  language?: string | undefined;

  // biome-ignore lint/suspicious/noExplicitAny: Hehe
  features?: DeepPartial<EnvelopeEditorSettings> & Record<string, any>;
  onEnvelopeUpdated?: (data: {
    externalId: string | null;
    envelopeId: string;
  }) => void;
};
import { CssVars } from "./css-vars";
import type { DeepPartial, EnvelopeEditorSettings } from "./features-type";

function EmbedUpdateEnvelope(props: EmbedUpdateEnvelopeProps) {
  const __iframe = useRef<HTMLIFrameElement>(null);
  function src() {
    const appHost = props.host || "https://app.documenso.com";
    const encodedOptions = btoa(
      encodeURIComponent(
        JSON.stringify({
          externalId: props.externalId,
          user: props.user,
          features: props.features,
          css: props.css,
          cssVars: props.cssVars,
          darkModeDisabled: props.darkModeDisabled,
          language: props.language,
        })
      )
    );
    const srcUrl = new URL(
      `/embed/v2/authoring/envelope/edit/${props.envelopeId}`,
      appHost
    );
    srcUrl.searchParams.set("token", props.presignToken);
    srcUrl.hash = encodedOptions;
    return srcUrl.toString();
  }

  function sandbox() {
    // biome-ignore lint/suspicious/noExplicitAny: Mitosis types `sandbox` as a single token, but the attribute is space-separated.
    return "allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox allow-storage-access-by-user-activation" as any;
  }

  function handleMessage(event: MessageEvent) {
    if (__iframe.current?.contentWindow === event.source) {
      switch (event.data.type) {
        case "envelope-updated":
          props.onEnvelopeUpdated?.({
            envelopeId: event.data.envelopeId,
            externalId: event.data.externalId,
          });
          break;
      }
    }
  }

  useEffect(() => {
    window.addEventListener("message", handleMessage);
  }, []);

  useEffect(() => {
    return () => {
      window.removeEventListener("message", handleMessage);
    };
  }, []);

  return (
    <iframe
      ref={__iframe}
      className={props.className}
      src={src()}
      sandbox={sandbox()}
    />
  );
}

export default EmbedUpdateEnvelope;
