// packages/svelte/src/sign-document.svelte
<script context="module" lang="ts">
  export type EmbedSignDocumentProps = {
    className?: string;
    host?: string;
    token: string; // @src: /apps/web/src/app/embed/direct/[[...url]]/schema

    css?: string | undefined;
    cssVars?: (CssVars & Record<string, string>) | undefined;
    darkModeDisabled?: boolean | undefined;
    name?: string | undefined;
    lockName?: boolean | undefined;
    email?: string | undefined;
    lockEmail?: boolean | undefined;
    allowDocumentRejection?: boolean | undefined; // Additional props to be passed to the iframe, used for testing out features
    // prior to being added to the main props

    additionalProps?: Record<string, string | number | boolean> | undefined;
    onDocumentReady?: () => void;
    onDocumentCompleted?: (data: {
      token: string;
      documentId: number;
      recipientId: number;
    }) => void;
    onDocumentError?: (error: string) => void;
    onDocumentRejected?: (data: {
      token: string;
      documentId: number;
      recipientId: number;
      reason: string;
    }) => void;
  };
</script>

<script lang="ts">
  import { onDestroy, onMount } from "svelte";

  import { CssVars } from "./css-vars";

  export let host: EmbedSignDocumentProps["host"] = undefined;
  export let name: EmbedSignDocumentProps["name"] = undefined;
  export let lockName: EmbedSignDocumentProps["lockName"] = undefined;
  export let email: EmbedSignDocumentProps["email"] = undefined;
  export let lockEmail: EmbedSignDocumentProps["lockEmail"] = undefined;
  export let css: EmbedSignDocumentProps["css"] = undefined;
  export let cssVars: EmbedSignDocumentProps["cssVars"] = undefined;
  export let darkModeDisabled: EmbedSignDocumentProps["darkModeDisabled"] =
    undefined;
  export let allowDocumentRejection: EmbedSignDocumentProps["allowDocumentRejection"] =
    undefined;
  export let additionalProps: EmbedSignDocumentProps["additionalProps"] =
    undefined;
  export let token: EmbedSignDocumentProps["token"];
  export let onDocumentReady: EmbedSignDocumentProps["onDocumentReady"] =
    undefined;
  export let onDocumentCompleted: EmbedSignDocumentProps["onDocumentCompleted"] =
    undefined;
  export let onDocumentError: EmbedSignDocumentProps["onDocumentError"] =
    undefined;
  export let onDocumentRejected: EmbedSignDocumentProps["onDocumentRejected"] =
    undefined;
  export let className: EmbedSignDocumentProps["className"] = undefined;

  function handleMessage(event: MessageEvent) {
    if (__iframe?.contentWindow === event.source) {
      switch (event.data.action) {
        case "document-ready":
          onDocumentReady?.();
          break;

        case "document-completed":
          onDocumentCompleted?.(event.data.data);
          break;

        case "document-error":
          onDocumentError?.(event.data.data);
          break;

        case "document-rejected":
          onDocumentRejected?.(event.data.data);
          break;
      }
    }
  }
  $: src = () => {
    const appHost = host || "https://app.documenso.com";
    const encodedOptions = btoa(
      encodeURIComponent(
        JSON.stringify({
          name: name,
          lockName: lockName,
          email: email,
          lockEmail: lockEmail,
          css: css,
          cssVars: cssVars,
          darkModeDisabled: darkModeDisabled,
          allowDocumentRejection: allowDocumentRejection,
          ...additionalProps,
        })
      )
    );
    const srcUrl = new URL(`/embed/sign/${token}`, appHost);
    return `${srcUrl}#${encodedOptions}`;
  };

  let __iframe;

  onMount(() => {
    window.addEventListener("message", handleMessage);
  });

  onDestroy(() => {
    window.removeEventListener("message", handleMessage);
  });
</script>

<iframe bind:this={__iframe} class={className} src={src()} />

// packages/solid/src/sign-document.tsx
import { onMount, createSignal, createMemo } from "solid-js";

export type EmbedSignDocumentProps = {
  className?: string;
  host?: string;
  token: string; // @src: /apps/web/src/app/embed/direct/[[...url]]/schema

  css?: string | undefined;
  cssVars?: (CssVars & Record<string, string>) | undefined;
  darkModeDisabled?: boolean | undefined;
  name?: string | undefined;
  lockName?: boolean | undefined;
  email?: string | undefined;
  lockEmail?: boolean | undefined;
  allowDocumentRejection?: boolean | undefined; // Additional props to be passed to the iframe, used for testing out features
  // prior to being added to the main props

  additionalProps?: Record<string, string | number | boolean> | undefined;
  onDocumentReady?: () => void;
  onDocumentCompleted?: (data: {
    token: string;
    documentId: number;
    recipientId: number;
  }) => void;
  onDocumentError?: (error: string) => void;
  onDocumentRejected?: (data: {
    token: string;
    documentId: number;
    recipientId: number;
    reason: string;
  }) => void;
};

import { CssVars } from "./css-vars";

function EmbedSignDocument(props: EmbedSignDocumentProps) {
  const src = createMemo(() => {
    const appHost = props.host || "https://app.documenso.com";
    const encodedOptions = btoa(
      encodeURIComponent(
        JSON.stringify({
          name: props.name,
          lockName: props.lockName,
          email: props.email,
          lockEmail: props.lockEmail,
          css: props.css,
          cssVars: props.cssVars,
          darkModeDisabled: props.darkModeDisabled,
          allowDocumentRejection: props.allowDocumentRejection,
          ...props.additionalProps,
        })
      )
    );
    const srcUrl = new URL(`/embed/sign/${props.token}`, appHost);
    return `${srcUrl}#${encodedOptions}`;
  });

  function handleMessage(event: MessageEvent) {
    if (__iframe?.contentWindow === event.source) {
      switch (event.data.action) {
        case "document-ready":
          props.onDocumentReady?.();
          break;

        case "document-completed":
          props.onDocumentCompleted?.(event.data.data);
          break;

        case "document-error":
          props.onDocumentError?.(event.data.data);
          break;

        case "document-rejected":
          props.onDocumentRejected?.(event.data.data);
          break;
      }
    }
  }

  let __iframe: HTMLIFrameElement;

  onMount(() => {
    window.addEventListener("message", handleMessage);
  });

  return (
    <>
      <iframe class={props.className} ref={__iframe!} src={src()}></iframe>
    </>
  );
}

export default EmbedSignDocument;
