// packages/svelte/src/update-document.svelte
<script context="module" lang="ts">
  export type EmbedUpdateDocumentProps = {
    className?: string;
    host?: string;
    presignToken: string;
    documentId: number;
    externalId?: string;

    // @src: /apps/web/src/app/embed/direct/[[...url]]/schema
    css?: string | undefined;
    cssVars?: (CssVars & Record<string, string>) | undefined;
    darkModeDisabled?: boolean | undefined;
    language?: string | undefined;
    features?: {
      allowConfigureSignatureTypes?: boolean;
      allowConfigureLanguage?: boolean;
      allowConfigureDateFormat?: boolean;
      allowConfigureTimezone?: boolean;
      allowConfigureRedirectUrl?: boolean;
      allowConfigureCommunication?: boolean;
    };
    onlyEditFields?: boolean | undefined;

    // Additional props to be passed to the iframe, used for testing out features
    // prior to being added to the main props
    additionalProps?: Record<string, string | number | boolean> | undefined;
    onDocumentUpdated?: (data: {
      externalId: string;
      documentId: number;
    }) => void;
  };
</script>

<script lang="ts">
  import { onDestroy, onMount } from "svelte";

  import { CssVars } from "./css-vars";

  export let host: EmbedUpdateDocumentProps["host"] = undefined;
  export let presignToken: EmbedUpdateDocumentProps["presignToken"];
  export let externalId: EmbedUpdateDocumentProps["externalId"] = undefined;
  export let features: EmbedUpdateDocumentProps["features"] = undefined;
  export let css: EmbedUpdateDocumentProps["css"] = undefined;
  export let cssVars: EmbedUpdateDocumentProps["cssVars"] = undefined;
  export let darkModeDisabled: EmbedUpdateDocumentProps["darkModeDisabled"] =
    undefined;
  export let language: EmbedUpdateDocumentProps["language"] = undefined;
  export let onlyEditFields: EmbedUpdateDocumentProps["onlyEditFields"] =
    undefined;
  export let additionalProps: EmbedUpdateDocumentProps["additionalProps"] =
    undefined;
  export let documentId: EmbedUpdateDocumentProps["documentId"];
  export let onDocumentUpdated: EmbedUpdateDocumentProps["onDocumentUpdated"] =
    undefined;
  export let className: EmbedUpdateDocumentProps["className"] = undefined;

  function handleMessage(event: MessageEvent) {
    if (__iframe?.contentWindow === event.source) {
      switch (event.data.type) {
        case "document-updated":
          onDocumentUpdated?.({
            documentId: event.data.documentId,
            externalId: event.data.externalId,
          });
          break;
      }
    }
  }
  $: src = () => {
    const appHost = host || "https://app.documenso.com";
    const encodedOptions = btoa(
      encodeURIComponent(
        JSON.stringify({
          token: presignToken,
          externalId: externalId,
          features: features,
          css: css,
          cssVars: cssVars,
          darkModeDisabled: darkModeDisabled,
          language: language,
          onlyEditFields: onlyEditFields,
          ...additionalProps,
        })
      )
    );
    const srcUrl = new URL(
      `/embed/v1/authoring/document/edit/${documentId}`,
      appHost
    );
    srcUrl.searchParams.set("token", presignToken);
    srcUrl.hash = encodedOptions;
    return srcUrl.toString();
  };
  $: sandbox = () => {
    // biome-ignore lint/suspicious/noExplicitAny: Mitosis types `sandbox` as a single token, but the attribute is space-separated.
    return "allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox allow-storage-access-by-user-activation" as any;
  };

  let __iframe;

  onMount(() => {
    window.addEventListener("message", handleMessage);
  });

  onDestroy(() => {
    window.removeEventListener("message", handleMessage);
  });
</script>

<iframe
  bind:this={__iframe}
  class={className}
  src={src()}
  sandbox={sandbox()}
/>

// packages/solid/src/update-document.tsx
import { onMount, createSignal, createMemo } from "solid-js";

export type EmbedUpdateDocumentProps = {
  className?: string;
  host?: string;
  presignToken: string;
  documentId: number;
  externalId?: string;

  // @src: /apps/web/src/app/embed/direct/[[...url]]/schema
  css?: string | undefined;
  cssVars?: (CssVars & Record<string, string>) | undefined;
  darkModeDisabled?: boolean | undefined;
  language?: string | undefined;
  features?: {
    allowConfigureSignatureTypes?: boolean;
    allowConfigureLanguage?: boolean;
    allowConfigureDateFormat?: boolean;
    allowConfigureTimezone?: boolean;
    allowConfigureRedirectUrl?: boolean;
    allowConfigureCommunication?: boolean;
  };
  onlyEditFields?: boolean | undefined;

  // Additional props to be passed to the iframe, used for testing out features
  // prior to being added to the main props
  additionalProps?: Record<string, string | number | boolean> | undefined;
  onDocumentUpdated?: (data: {
    externalId: string;
    documentId: number;
  }) => void;
};

import { CssVars } from "./css-vars";

function EmbedUpdateDocument(props: EmbedUpdateDocumentProps) {
  const src = createMemo(() => {
    const appHost = props.host || "https://app.documenso.com";
    const encodedOptions = btoa(
      encodeURIComponent(
        JSON.stringify({
          token: props.presignToken,
          externalId: props.externalId,
          features: props.features,
          css: props.css,
          cssVars: props.cssVars,
          darkModeDisabled: props.darkModeDisabled,
          language: props.language,
          onlyEditFields: props.onlyEditFields,
          ...props.additionalProps,
        })
      )
    );
    const srcUrl = new URL(
      `/embed/v1/authoring/document/edit/${props.documentId}`,
      appHost
    );
    srcUrl.searchParams.set("token", props.presignToken);
    srcUrl.hash = encodedOptions;
    return srcUrl.toString();
  });

  const sandbox = createMemo(() => {
    // biome-ignore lint/suspicious/noExplicitAny: Mitosis types `sandbox` as a single token, but the attribute is space-separated.
    return "allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox allow-storage-access-by-user-activation" as any;
  });

  function handleMessage(event: MessageEvent) {
    if (__iframe?.contentWindow === event.source) {
      switch (event.data.type) {
        case "document-updated":
          props.onDocumentUpdated?.({
            documentId: event.data.documentId,
            externalId: event.data.externalId,
          });
          break;
      }
    }
  }

  let __iframe!: HTMLIFrameElement;

  onMount(() => {
    window.addEventListener("message", handleMessage);
  });

  return (
    <>
      <iframe
        class={props.className}
        ref={__iframe!}
        src={src()}
        sandbox={sandbox()}
      ></iframe>
    </>
  );
}

export default EmbedUpdateDocument;
